name: Alv testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Pytest on ${{ matrix.os }} - ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6.15', '3.8.18', '3.12.9', '3.x']
        os: [ubuntu, windows, macos]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py develop
    - name: Test on ${{ matrix.os }} - ${{ matrix.python-version }}
      run: |
        python -m pytest tests/ -v
